QUESTIONS = [
    "Tell me about yourself.",
    "Can you walk me through your resume?",
    "Why are you interested in this job?",
    "What do you know about our company?",
    "Why should we hire you?",
    "What are your strengths?",
    "What are your weaknesses?",
    "Tell me about a challenge you faced and how you handled it.",
    "Describe a situation where you worked in a team.",
    "Tell me about a time you solved a difficult problem.",
    "What motivates you?",
    "Where do you see yourself in 5 years?",
    "How do you handle stress and pressure?",
    "Tell me about a time you failed and what you learned.",
    "What are your salary expectations?",
    "Why do you want to leave your current job?",
    "What are your career goals?",
    "How do you prioritize tasks?",
    "Describe a time you showed leadership.",
    "Tell me about a time you had a conflict with a coworker.",
    "How do you learn new technologies?",
    "What is your biggest achievement?",
    "What makes you a good team player?",
    "How do you handle deadlines?",
    "What have you done to improve your skills recently?",
    "Explain a technical project you worked on.",
    "What role do you play in group projects?",
    "How do you handle feedback?",
    "Why did you choose your field of study?",
    "Describe your ideal work environment.",
    "Tell me about a time you went above and beyond.",
    "How do you stay organized?",
    "What qualities should a good employee have?",
    "How do you handle mistakes?",
    "Describe your work style.",
    "What do you expect from your manager?",
    "How do you handle multiple tasks at the same time?",
    "What makes you unique?",
    "Do you prefer working alone or in a team?",
    "What are your hobbies and interests?",
    "Tell me about a time you met a tight deadline.",
    "How do you approach new projects?",
    "Do you have any questions for us?",
    "Explain a time you disagreed with your manager.",
    "How do you keep yourself updated with industry trends?",
    "What is one thing you would like to improve about yourself?",
    "What do you think makes a successful team?",
    "Tell me something that is not on your resume.",
    "Why do you want to work in this industry?"
]

